
P=./plots/CL_1DFIR_Profiling* ./plots/CL_1DFIR_Profile_Ops* ./plots/Cimpl_1DFIR_Profiling* ./plots/Cimpl_1DFIR_Profile_Ops*

all:
	Rscript CL_1DFIR_Profiling.R
	Rscript CL_1DFIR_Profile_Ops.R
	Rscript Cimpl_1DFIR_Profiling.R
	Rscript Cimpl_1DFIR_Profile_Ops.R
